baseURL = '/'
languageCode = 'en-us'
title = 'VitaSpire'
theme = 'ananke'

[params]
  description = "VitaSpire"
  author = "VitaSpire"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 5

[[menu.main]]
  name = "About Us"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Products"
  url = "/products/"
  weight = 20

[[menu.main]]
  name = "Contact Us"
  url = "/contact/"
  weight = 30
