baseURL = '/'
languageCode = 'en-us'
title = 'VitaSpire'
theme = 'ananke'

[params]
  description = "VitaSpire"
  author = "VitaSpire"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 5

[[menu.main]]
  name = "About Us"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Biomedical & Health Materials"
  url = "/products/biomedical-health-materials/"
  weight = 20

[[menu.main]]
  name = "Human Nutrition Solutions"
  url = "/products/human-nutrition-solutions/"
  weight = 25

[[menu.main]]
  name = "Advanced Industrial Materials"
  url = "/products/advanced-industrial-materials/"
  weight = 30

[[menu.main]]
  name = "Contact Us"
  url = "/contact/"
  weight = 35
